### ISSUE TITLE
Reference to an existing yolov5 server

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/fastapi-yolov5#1]
@danellecline Just making you aware that there's an existing yolov5 server we're using in production at https://github.com/mbari-org/pythia. The front is at http://perceptron.shore.mbari.org:8080, the api docs are at http://perceptron.shore.mbari.org:8080/q/swagger-ui/

**Comment by hohonuuli** [comment]
@danellecline Can you add endpoints that match the existing pythia API? Then this could be used as an alternative or drop in replacement. Also, is there a way to set the model used at runtime rather than build time (e.g. through an env variable or command line param?

**Comment by danellecline** [comment]
@hohonuuli I will look at matching the existing API to pythia. The FastAPI framework is flexible, so that may be straightforward.  I'm focusing on scaling now, but I will return to a uniform API when that is done.

**Comment by danellecline** [comment]
I finished the scaling tests on i2MAP by running this through every second of most recorded videos. Worked great and took just a few days to run.     This confirms that it can be used at scale quickly for a larger collection.

I made a few modifications to the API to be closer to Pythia, but will stop here unless there is a compelling need as I am out of time in the core VARS project.

The API is here and restricted to MBARI traffic http://fasta-fasta-1d0o3gwgv046e-143598223.us-west-2.elb.amazonaws.com/docs#/

**Comment by danellecline** [comment]
This will be part of the workflow to mine for Ctenophora sp. A for the BioDiversity project.  If there is interest in using it elsewhere, instructions for deploying a new model can be found at [fastapi-yolov5](http://github.com/mbari-org/fastapi-yolov5).  Closing this issue. 
@hohonuuli @beroe  @duane-edgington @kgomes
